<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * GST billing (online-only). A bill is created on the server in one
     * transaction: invoice number from the shop's series, items, and the
     * stock movements that sell the stock. Money is integer paise.
     */
    public function up(): void
    {
        // One gap-free counter per shop per Indian financial year (Apr-Mar).
        // Bumped under a row lock inside the bill transaction, so a failed
        // bill never uses up a number and two bills never share one.
        Schema::create('invoice_series', function (Blueprint $table) {
            $table->id();
            $table->foreignId('shop_id')->constrained()->cascadeOnDelete();
            $table->string('fy', 5); // "26-27"
            $table->unsignedInteger('last_seq')->default(0);
            $table->timestamps();
            $table->unique(['shop_id', 'fy']);
        });

        Schema::create('bills', function (Blueprint $table) {
            // Generated by the device and sent with the request; a retry with
            // the same id returns the bill instead of creating a second one.
            $table->uuid('id')->primary();
            $table->foreignId('shop_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            $table->string('device_id', 64)->nullable();

            $table->string('invoice_no', 32); // PREFIX/26-27/000042
            $table->string('fy', 5);
            $table->unsignedInteger('seq');
            $table->date('bill_date');

            // The customer's party (accounts) when chosen; credit bills need
            // one. The customer fields below are copied onto the bill.
            $table->uuid('party_id')->nullable();
            // Customer as printed on this bill.
            $table->string('customer_name', 100)->nullable();
            $table->string('customer_phone', 20)->nullable();
            $table->string('customer_gstin', 15)->nullable();
            $table->string('customer_state_code', 2)->nullable();
            $table->string('customer_address', 500)->nullable();
            $table->string('place_of_supply', 2)->nullable();
            $table->boolean('is_inter_state')->default(false);

            // Seller details as printed on the invoice at billing time, so a
            // reprint shows them even if the shop's details change later.
            $table->json('seller');

            $table->unsignedBigInteger('subtotal_paise'); // MRP x qty, before discount
            $table->unsignedBigInteger('discount_paise');
            $table->unsignedBigInteger('taxable_paise');
            $table->unsignedBigInteger('cgst_paise');
            $table->unsignedBigInteger('sgst_paise');
            $table->unsignedBigInteger('igst_paise');
            $table->bigInteger('round_off_paise'); // -49..+50, to a whole rupee
            $table->unsignedBigInteger('total_paise');

            $table->string('payment_mode', 8); // cash|upi|card|credit
            $table->string('status', 12)->default('final'); // final|cancelled
            $table->timestamp('cancelled_at')->nullable();
            $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('cancel_reason')->nullable();
            $table->timestamps();

            $table->unique(['shop_id', 'fy', 'seq']);
            $table->unique(['shop_id', 'invoice_no']);
            $table->index(['shop_id', 'bill_date']);
            $table->index(['shop_id', 'party_id']);
        });

        // One row per batch sold. Names, HSN, batch and prices are copied
        // so the invoice never changes when the product is edited later.
        Schema::create('bill_items', function (Blueprint $table) {
            $table->id();
            $table->uuid('bill_id');
            $table->foreign('bill_id')->references('id')->on('bills')->cascadeOnDelete();
            $table->unsignedSmallInteger('line_no');
            $table->uuid('product_id');
            $table->uuid('batch_id');
            $table->string('name');
            $table->string('hsn', 16)->nullable();
            $table->string('unit', 32)->nullable();
            $table->string('batch_no', 64)->nullable();
            $table->date('expiry_date')->nullable();
            $table->unsignedInteger('qty_units');
            $table->unsignedBigInteger('mrp_paise'); // per unit, incl. GST
            $table->unsignedBigInteger('rate_paise'); // per unit, excl. GST, after discount
            $table->unsignedInteger('discount_bp')->default(0);
            $table->unsignedBigInteger('discount_paise')->default(0);
            $table->unsignedInteger('gst_rate_bp');
            $table->unsignedBigInteger('taxable_paise');
            $table->unsignedBigInteger('cgst_paise');
            $table->unsignedBigInteger('sgst_paise');
            $table->unsignedBigInteger('igst_paise');
            $table->unsignedBigInteger('total_paise'); // taxable + tax
            $table->index('bill_id');
            $table->index('batch_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('bill_items');
        Schema::dropIfExists('bills');
        Schema::dropIfExists('invoice_series');
    }
};
